-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxWXfDfBmnyHXookU
H+gyZSDIRMtLvkBIHTsrXKHbeqagCgYIKoZIzj0DAQehRANCAARkJlWINsre9ii5
3YtC0RadH4O09a+PLwe07Zy8tupqFdp8/f8HKCb+E0nkjUwVmUwg/45yVSoStpIm
LUIuCd2p
-----END PRIVATE KEY-----